version: '3'
services:
  prisma:
    image: prismagraphql/prisma:1.34
    restart: always
    ports:
    - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        # uncomment the next line and provide the env var PRISMA_MANAGEMENT_API_SECRET=my-secret to activate cluster security
        # managementApiSecret: my-secret
        databases:
          default:
            connector: postgres
            host: ec2-52-202-22-140.compute-1.amazonaws.com
            database: db9psks1su8e8u
            schema: public
            user: isdxsxiywalelr
            password: 12a93ed70da05debc2d45f176f520a0c30662b8ed91613eebc1bcf881326f5f3
            ssl: true
            rawAccess: true
            port: '5432'
            migrations: true